language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env: STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=YES
    - os: linux
      dist: xenial
      compiler: clang
      env: STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=YES
    - os: osx
      compiler: clang
      env: STRUS_WITH_VECTOR=NO STRUS_WITH_PATTERN=NO STRUS_WITH_WEBSERVICE=YES
sudo: required
branches:
  only:
    - master
before_install:
- chmod +x dist/travis/*.sh
- dist/travis/before_script.sh
script:
- dist/travis/script.sh
