#ifndef ERROR_CODES_H
#define ERROR_CODES_H

const int ERROR_BASE										= 1000;

// generic protocol errors

const int ERROR_ILLEGAL_METHOD								= ERROR_BASE + 1;
const int ERROR_IILLEGAL_JSON								= ERROR_BASE + 2;

// errors in index management

const int ERROR_INDEX 										= 2000;

const int ERROR_INDEX_ILLEGAL_JSON							= ERROR_INDEX + 1;

const int ERROR_INDEX_CREATE_CMD							= ERROR_INDEX + 100;
const int ERROR_INDEX_CREATE_DATABASE_EXISTS				= ERROR_INDEX_CREATE_CMD + 1;
const int ERROR_INDEX_CREATE_DATABASE_INTERFACE 			= ERROR_INDEX_CREATE_CMD + 2;
const int ERROR_INDEX_CREATE_STORAGE_INTERFACE	 			= ERROR_INDEX_CREATE_CMD + 3;
const int ERROR_INDEX_CREATE_CMD_CREATE_DATABASE			= ERROR_INDEX_CREATE_CMD + 4;
const int ERROR_INDEX_CREATE_CMD_CREATE_CLIENT				= ERROR_INDEX_CREATE_CMD + 5;
const int ERROR_INDEX_CREATE_CMD_MKDIR_STORAGE_DIR			= ERROR_INDEX_CREATE_CMD + 6;

const int ERROR_INDEX_DESTROY_CMD 							= ERROR_INDEX + 200;
const int ERROR_INDEX_DESTROY_CMD_NO_SUCH_DATABASE			= ERROR_INDEX_DESTROY_CMD + 1;
const int ERROR_INDEX_DESTROY_CMD_DESTROY_DATABASE			= ERROR_INDEX_DESTROY_CMD + 2;

const int ERROR_INDEX_STATS_CMD								= ERROR_INDEX + 300;
const int ERROR_INDEX_STATS_CMD_ILLEGAL_STORAGE_DIR			= ERROR_INDEX_STATS_CMD + 1;
const int ERROR_INDEX_STATS_CMD_NO_SUCH_DATABASE			= ERROR_INDEX_STATS_CMD + 2;
const int ERROR_INDEX_STATS_CMD_CREATE_DATABASE_CLIENT		= ERROR_INDEX_STATS_CMD + 3;
const int ERROR_INDEX_STATS_CMD_CREATE_STORAGE_CLIENT		= ERROR_INDEX_STATS_CMD + 4;

const int ERROR_INDEX_CONFIG_CMD							= ERROR_INDEX + 400;
const int ERROR_INDEX_CONFIG_CMD_ILLEGAL_STORAGE_DIR		= ERROR_INDEX_CONFIG_CMD + 1;
const int ERROR_INDEX_CONFIG_CMD_NO_SUCH_DATABASE			= ERROR_INDEX_CONFIG_CMD + 2;
const int ERROR_INDEX_CONFIG_CMD_CREATE_DATABASE_CLIENT		= ERROR_INDEX_CONFIG_CMD + 3;
const int ERROR_INDEX_CONFIG_CMD_CREATE_STORAGE_CLIENT		= ERROR_INDEX_CONFIG_CMD + 4;
const int ERROR_INDEX_CONFIG_CMD_CREATE_METADATA_READER		= ERROR_INDEX_CONFIG_CMD + 5;

// errors in document management

const int ERROR_DOCUMENT									= 3000;

const int ERROR_DOCUMENT_INSERT_CMD							= ERROR_DOCUMENT + 100;
const int ERROR_DOCUMENT_INSERT_CMD_ILLEGAL_STORAGE_DIR		= ERROR_DOCUMENT_INSERT_CMD + 1;
const int ERROR_DOCUMENT_INSERT_CMD_NO_SUCH_DATABASE		= ERROR_DOCUMENT_INSERT_CMD + 2;
const int ERROR_DOCUMENT_INSERT_CMD_CREATE_DATABASE_CLIENT	= ERROR_DOCUMENT_INSERT_CMD + 3;
const int ERROR_DOCUMENT_INSERT_CMD_CREATE_STORAGE_CLIENT	= ERROR_DOCUMENT_INSERT_CMD + 4;
const int ERROR_DOCUMENT_INSERT_CMD_CREATE_STORAGE_TRANSACTION = ERROR_DOCUMENT_INSERT_CMD + 5;
const int ERROR_DOCUMENT_INSERT_ILLEGAL_JSON				= ERROR_DOCUMENT_INSERT_CMD + 6;	

const int ERROR_DOCUMENT_EXISTS_CMD							= ERROR_DOCUMENT + 200;
const int ERROR_DOCUMENT_EXISTS_CMD_ILLEGAL_STORAGE_DIR		= ERROR_DOCUMENT_EXISTS_CMD + 1;
const int ERROR_DOCUMENT_EXISTS_CMD_NO_SUCH_DATABASE		= ERROR_DOCUMENT_EXISTS_CMD + 2;
const int ERROR_DOCUMENT_EXISTS_CMD_CREATE_DATABASE_CLIENT	= ERROR_DOCUMENT_EXISTS_CMD + 3;
const int ERROR_DOCUMENT_EXISTS_CMD_CREATE_STORAGE_CLIENT	= ERROR_DOCUMENT_EXISTS_CMD + 4;
const int ERROR_DOCUMENT_EXISTS_CMD_CREATE_STORAGE_TRANSACTION = ERROR_DOCUMENT_EXISTS_CMD + 5;
const int ERROR_DOCUMENT_EXISTS_ILLEGAL_JSON				= ERROR_DOCUMENT_EXISTS_CMD + 6;	

// errors in query

#endif
